[package]
name = "k-means"
version = "0.2.0"
authors = ["Patrick <entscheidungsproblem@protonmail.com>"]

[dependencies]
image = "0.18.0"
rand = "0.4.2"
rayon = "1.0.1"
palette = "0.3.0"
clap = {version = "2.32.0", features = ["yaml"]}
